apiVersion: apps/v1
kind: Deployment
metadata:
  name: kv-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kv-api
  template:
    metadata:
      labels:
        app: kv-api
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: kv-api
                topologyKey: kubernetes.io/hostname
      containers:
        - name: api
          image: kvstore:local
          imagePullPolicy: IfNotPresent
          env:
            - name: ETCD_ENDPOINTS
              value: http://etcd-0.etcd:2379,http://etcd-1.etcd:2379,http://etcd-2.etcd:2379
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 2
            periodSeconds: 2
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: "1"
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kv-api
spec:
  type: NodePort
  selector:
    app: kv-api
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30080
